// SafeScan AI - Production Database
// Comprehensive list of E-numbers, additives, and allergens with multi-language support (English & French)

const INGREDIENTS_DB = [
    // --- HIGH RISK (Category 3: DANGER / AVOID) ---
    { name: "Tartrazine", code: "E102", alt: "E102 / Tartrazină / Tartrazine / Jaune de tartrazine", risk: 3, desc: "Artificial yellow color. Can cause hyperactivity, asthma, and severe allergic reactions. / Colorant galben artificial. Poate provoca hiperactivitate și astm.", category: "Colorant" },
    { name: "Quinoline Yellow", code: "E104", alt: "E104 / Jaune de quinoléine / Galben de chinolină", risk: 3, desc: "Synthetic dye. Linked to dermatitis and childhood hyperactivity. / Colorant sintetic. Asociat cu dermatita și hiperactivitatea.", category: "Colorant" },
    { name: "Sunset Yellow FCF", code: "E110", alt: "E110 / Jaune soleil FCF / Galben amurg FCF", risk: 3, desc: "Orange-yellow dye. Can cause hay fever, hives, and stomach upset. / Colorant portocaliu. Poate cauza alergii și probleme gastrice.", category: "Colorant" },
    { name: "Carmoisine", code: "E122", alt: "E122 / Azorubine / Carmoizină / Azorubină", risk: 3, desc: "Red dye. Increases risk of hyperactivity. Avoid if asthmatic. / Colorant roșu. Crește riscul de hiperactivitate.", category: "Colorant" },
    { name: "Amaranth", code: "E123", alt: "E123 / Amarante / Amarant", risk: 3, desc: "Dark red dye. Potentially carcinogenic. Banned in the USA. / Colorant roșu închis. Potențial cancerigen.", category: "Colorant" },
    { name: "Ponceau 4R", code: "E124", alt: "E124 / Roșu Ponceau 4R", risk: 3, desc: "Bright red dye. Linked to cancer in animals and hyperactivity. / Colorant roșu aprins. Asociat cu riscuri de cancer.", category: "Colorant" },
    { name: "Erythrosine", code: "E127", alt: "E127 / Eritrozină / Érythrosine", risk: 3, desc: "Cherry pink dye. Can interfere with thyroid function. / Colorant roz. Poate afecta tiroida.", category: "Colorant" },
    { name: "Allura Red AC", code: "E129", alt: "E129 / Rouge allura / Roșu Allura AC", risk: 3, desc: "Orange-red dye. Suspected of being a carcinogen. / Colorant roșu-portocaliu. Suspectat de efecte cancerigene.", category: "Colorant" },
    { name: "Patent Blue V", code: "E131", alt: "E131 / Bleu patenté V / Albastru Patent V", risk: 3, desc: "Deep blue dye. Can cause skin rashes. / Colorant albastru închis. Poate cauza erupții cutanate.", category: "Colorant" },
    { name: "Indigotine", code: "E132", alt: "E132 / Indigo carmine / Indigo carmin", risk: 3, desc: "Blue dye. Associated with high blood pressure and skin issues. / Colorant albastru. Asociat cu hipertensiune.", category: "Colorant" },
    { name: "Brilliant Blue FCF", code: "E133", alt: "E133 / Bleu brillant FCF / Albastru briliant FCF", risk: 3, desc: "Bright blue dye. Can cross the blood-brain barrier. / Colorant albastru strălucitor. Poate trece de bariera sange-creier.", category: "Colorant" },
    { name: "Green S", code: "E142", alt: "E142 / Vert S / Verde S", risk: 3, desc: "Green dye. Linked to allergic skin reactions. / Colorant verde. Asociat cu reacții alergice cutanate.", category: "Colorant" },
    { name: "Brilliant Black BN", code: "E151", alt: "E151 / Noir brillant BN / Negru briliant BN", risk: 3, desc: "Black dye. Can cause intestinal distress. / Colorant negru. Poate cauza probleme intestinale.", category: "Colorant" },
    { name: "Brown FK", code: "E154", alt: "E154 / Brun FK", risk: 3, desc: "Brown dye. Can damage internal organs. / Colorant maro. Poate afecta organele interne.", category: "Colorant" },
    { name: "Brown HT", code: "E155", alt: "E155 / Brun HT", risk: 3, desc: "Brown dye. Can cause allergic reactions. / Colorant maro. Poate cauza reacții alergice.", category: "Colorant" },
    { name: "Benzoic Acid", code: "E210", alt: "E210 / Acide benzoïque / Acid benzoic", risk: 3, desc: "Preservative. Can cause neurological disorders and severe allergies. / Conservant. Poate cauza tulburări neurologice.", category: "Preservative" },
    { name: "Sodium Benzoate", code: "E211", alt: "E211 / Benzoate de sodium / Benzoat de sodiu", risk: 3, desc: "Forms benzene (carcinogen) with Vit C. Highly toxic. / Formează benzen (cancerigen) cu Vit C. Foarte toxic.", category: "Preservative" },
    { name: "Potassium Benzoate", code: "E212", alt: "E212 / Benzoate de potassium / Benzoat de potasiu", risk: 3, desc: "Preservative. Similar risk to Sodium Benzoate. / Conservant. Risc similar cu benzoatul de sodiu.", category: "Preservative" },
    { name: "Calcium Benzoate", code: "E213", alt: "E213 / Benzoat de calciu", risk: 3, desc: "Preservative. Linked to asthma and hyperactivity. / Conservant. Asociat cu astm și hiperactivitate.", category: "Preservative" },
    { name: "Ethylparaben", code: "E214", alt: "E214 / Etilparaben / Paraben", risk: 3, desc: "Preservative. Potential endocrine disruptor. / Conservant. Potențial perturbator endocrin.", category: "Preservative" },
    { name: "Sodium Ethylparaben", code: "E215", alt: "E215 / Etilparaben de sodiu", risk: 3, desc: "Preservative. Banned in some countries. / Conservant. Interzis în unele țări.", category: "Preservative" },
    { name: "Propylparaben", code: "E216", alt: "E216 / Propilparaben", risk: 3, desc: "Preservative. Endocrine disruptor concern. / Conservant. Risc de perturbare endocrină.", category: "Preservative" },
    { name: "Sodium Propylparaben", code: "E217", alt: "E217 / Propilparaben de sodiu", risk: 3, desc: "Preservative. Highly toxic for some. / Conservant. Foarte toxic pentru unii.", category: "Preservative" },
    { name: "Methylparaben", code: "E218", alt: "E218 / Metilparaben", risk: 3, desc: "Preservative. Can cause skin reactions. / Conservant. Poate cauza reacții cutanate.", category: "Preservative" },
    { name: "Sodium Methylparaben", code: "E219", alt: "E219 / Metilparaben de sodiu", risk: 3, desc: "Preservative. Risk of allergies. / Conservant. Risc de alergii.", category: "Preservative" },
    { name: "Sulphur Dioxide", code: "E220", alt: "E220 / Anhydride sulfureux / Dioxid de sulf / Sulfiți / Sultfites", risk: 3, desc: "Dangerous for asthmatics. Destroys vitamins. / Periculos pentru astmatici. Distruge vitaminele.", category: "Preservative" },
    { name: "Sodium Sulphite", code: "E221", alt: "E221 / Sulfit de sodiu", risk: 3, desc: "Preservative. Can cause severe allergic reactions. / Conservant. Poate cauza reacții alergice severe.", category: "Preservative" },
    { name: "Sodium Hydrogen Sulphite", code: "E222", alt: "E222 / Bisulfit de sodiu", risk: 3, desc: "Preservative. Toxic when inhaled. / Conservant. Toxic prin inhalare.", category: "Preservative" },
    { name: "Sodium Metabisulphite", code: "E223", alt: "E223 / Metabisulfit de sodiu", risk: 3, desc: "Common preservative in dried fruits. / Conservant în fructe uscate.", category: "Preservative" },
    { name: "Potassium Metabisulphite", code: "E224", alt: "E224 / Metabisulfit de potasiu", risk: 3, desc: "Preservative. Dangerous for asthmatics. / Conservant. Periculos pentru astmatici.", category: "Preservative" },
    { name: "Calcium Sulphite", code: "E226", alt: "E226 / Sulfit de calciu", risk: 3, desc: "Preservative. May cause intestinal distress. / Conservant. Poate cauza probleme intestinale.", category: "Preservative" },
    { name: "Calcium Hydrogen Sulphite", code: "E227", alt: "E227 / Bisulfit de calciu", risk: 3, desc: "Preservative. Risk of asthma attacks. / Conservant. Risc de atacuri de astm.", category: "Preservative" },
    { name: "Potassium Hydrogen Sulphite", code: "E228", alt: "E228 / Bisulfit de potasiu", risk: 3, desc: "Preservative. Not recommended for children. / Conservant. Nerecomandat copiilor.", category: "Preservative" },
    { name: "Nisin", code: "E234", alt: "E234 / Nizină", risk: 3, desc: "Antibiotic used as preservative. / Antibiotic utilizat ca și conservant.", category: "Preservative" },
    { name: "Natamycin", code: "E235", alt: "E235 / Natamicină", risk: 3, desc: "Antifungal agent. Can cause nausea. / Agent antifungic. Poate cauza greață.", category: "Preservative" },
    { name: "Potassium Nitrite", code: "E249", alt: "E249 / Nitrit de potasiu", risk: 3, desc: "Preservative. May affect oxygen transport. / Conservant. Poate afecta transportul oxigenului.", category: "Preservative" },
    { name: "Sodium Nitrite", code: "E250", alt: "E250 / Nitrite de sodiu / Nitrit de sodiu", risk: 3, desc: "Highly carcinogenic in processed meats. / Foarte cancerigen în carnea procesată.", category: "Preservative" },
    { name: "Sodium Nitrate", code: "E251", alt: "E251 / Nitrate de sodiu / Nitrat de sodiu", risk: 3, desc: "Linked to heart disease and cancer. / Asociat cu boli de inimă și cancer.", category: "Preservative" },
    { name: "Potassium Nitrate", code: "E252", alt: "E252 / Nitrat de potasiu", risk: 3, desc: "Preservative and color stabilizer. / Conservant și stabilizator de culoare.", category: "Preservative" },
    { name: "Propyl Gallate", code: "E310", alt: "E310 / Galat de propil", risk: 3, desc: "Antioxidant. May cause stomach irritation. / Antioxidant. Poate cauza iritații gastrice.", category: "Antioxidant" },
    { name: "Octyl Gallate", code: "E311", alt: "E311 / Galat de octil", risk: 3, desc: "Antioxidant. Risk of skin reactions. / Antioxidant. Risc de reacții cutanate.", category: "Antioxidant" },
    { name: "Dodecyl Gallate", code: "E312", alt: "E312 / Galat de dodecil", risk: 3, desc: "Antioxidant. Linked to thyroid issues. / Antioxidant. Asociat cu probleme tiroidiene.", category: "Antioxidant" },
    { name: "BHA", code: "E320", alt: "E320 / Butylhydroxyanisole / Butilhidroxianizol", risk: 3, desc: "Potential human carcinogen. / Potențial cancerigen uman.", category: "Antioxidant" },
    { name: "BHT", code: "E321", alt: "E321 / Butylhydroxytoluène / Butilhidroxitoluen", risk: 3, desc: "Suspected endocrine disruptor. / Suspect de perturbare endocrină.", category: "Antioxidant" },
    { name: "Polyoxyethylene Sorbitan Monostearate", code: "E435", alt: "E435 / Polisorbat 60", risk: 3, desc: "Emulsifier. Linked to organ damage in animals. / Emulsifiant. Asociat cu daune la organe.", category: "Emulsifier" },
    { name: "Polyoxyethylene Sorbitan Monooleate", code: "E433", alt: "E433 / Polisorbat 80", risk: 3, desc: "Emulsifier. Can affect gut health and immunity. / Emulsifiant. Poate afecta imunitatea.", category: "Emulsifier" },
    { name: "MSG", code: "E621", alt: "E621 / Monosodium Glutamate / Glutamat monosodiu / Potențiator de aromă", risk: 3, desc: "Causes headaches and chest pain. / Cauzează dureri de cap și piept.", category: "Flavour Enhancer" },
    { name: "Disodium Inosinate", code: "E631", alt: "E631 / Inozinat disodic", risk: 3, desc: "Enhancer. Should be avoided by people with gout. / Evitați dacă aveți gută.", category: "Flavour Enhancer" },
    { name: "Disodium Guanylate", code: "E627", alt: "E627 / Guanilat disodic", risk: 3, desc: "Enhancer. Risk of allergic reactions. / Potențiator. Risc de reacții alergice.", category: "Flavour Enhancer" },
    { name: "Steviol Glycosides", code: "E960", alt: "E960 / Glicozide de steviol / Stevia", risk: 3, desc: "Sweetener. Controversial long-term effects. / Îndulcitor. Efecte pe termen lung controversate.", category: "Sweetener" },
    { name: "Acesulfame K", code: "E950", alt: "E950 / Acésulfame-K / Acesulfam K", risk: 3, desc: "Artificial sweetener. Controversial risks. / Îndulcitor artificial. Riscuri controversate.", category: "Sweetener" },
    { name: "Aspartame", code: "E951", alt: "E951 / Aspartam", risk: 3, desc: "Linked to headaches and neurotoxicity. / Asociat cu neurotoxicitate.", category: "Sweetener" },
    { name: "Cyclamate", code: "E952", alt: "E952 / Cyclamate de sodium / Ciclamat de sodiu", risk: 3, desc: "Banned in some countries. Cancer concern. / Interzis în unele țări. Risc de cancer.", category: "Sweetener" },
    { name: "Saccharin", code: "E954", alt: "E954 / Saccharine / Zaharină", risk: 3, desc: "Linked to cancer in laboratory animals. / Asociat cu cancerul la animale.", category: "Sweetener" },
    { name: "Sucralose", code: "E955", alt: "E955 / Sucraloză", risk: 3, desc: "Intense sweetener. May affect gut health. / Îndulcitor intens. Poate afecta flora intestinală.", category: "Sweetener" },
    { name: "Neohesperidin DC", code: "E959", alt: "E959 / Neohesperidină DC", risk: 3, desc: "Intense sweetener. Potential laxative. / Îndulcitor intens. Potențial laxativ.", category: "Sweetener" },
    { name: "Neotame", code: "E961", alt: "E961 / Neotam", risk: 3, desc: "Highly potent sweetener. Neurotoxin concern. / Îndulcitor extrem de potent.", category: "Sweetener" },
    { name: "Advantame", code: "E969", alt: "E969 / Advantam", risk: 3, desc: "New sweetener. Limited safety data. / Îndulcitor nou. Date de siguranță limitate.", category: "Sweetener" },

    // --- MEDIUM RISK (Category 2: CAUTION / MODERATE) ---
    { name: "Curcumin", code: "E100", alt: "E100 / Curcumină / Turmeric", risk: 2, desc: "Generally safe but can cause gallbladder symptoms. / General sigur, dar poate cauza probleme la bilă.", category: "Colorant" },
    { name: "Riboflavin", code: "E101", alt: "E101 / Riboflavină / Vitamina B2", risk: 2, desc: "Safe vitamin but can be GMO-sourced. / Vitamină sigură, dar poate proveni din surse OMG.", category: "Colorant" },
    { name: "Chlorophylls", code: "E140", alt: "E140 / Clorofilă", risk: 2, desc: "Natural green. Safe in moderation. / Verde natural. Sigur în moderație.", category: "Colorant" },
    { name: "Caramels", code: "E150a", alt: "E150a / Caramel simplu", risk: 2, desc: "The simplest caramel. Generally safe. / Cel mai simplu caramel. General sigur.", category: "Colorant" },
    { name: "Caustic Sulphite Caramel", code: "E150b", alt: "E150b / Caramel de sulfit caustic", risk: 2, desc: "Produced with sulphites. Risk for sensitive. / Produs cu sulfiți. Risc pentru cei sensibili.", category: "Colorant" },
    { name: "Ammonia Caramel", code: "E150c", alt: "E150c / Caramel ammoniacal / Caramel amoniacal", risk: 2, desc: "May contain toxic byproducts. / Poate conține subproduse toxice.", category: "Colorant" },
    { name: "Sulphite Ammonia Caramel", code: "E150d", alt: "E150d / Caramel au sulfite d'ammonium / Caramel sulfit de amoniu", risk: 2, desc: "Risk of bowel issues. / Risc de probleme intestinale.", category: "Colorant" },
    { name: "Vegetable Carbon", code: "E153", alt: "E153 / Cărbune vegetal", risk: 2, desc: "Safe but concerns about PAH impurities. / Sigur, dar poate conține impurități PAH.", category: "Colorant" },
    { name: "Anthocyanins", code: "E163", alt: "E163 / Antocianine", risk: 2, desc: "Natural pigments. Safe in low doses. / Pigmenți naturali. Sigur în doze mici.", category: "Colorant" },
    { name: "Sorbic Acid", code: "E200", alt: "E200 / Acide sorbique / Acid sorbic", risk: 2, desc: "Can cause skin irritation. / Poate cauza iritații ale pielii.", category: "Preservative" },
    { name: "Potassium Sorbate", code: "E202", alt: "E202 / Sorbate de potassium / Sorbat de potasiu", risk: 2, desc: "Common preservative. Generally safe. / Conservant comun. General sigur.", category: "Preservative" },
    { name: "Calcium Sorbate", code: "E203", alt: "E203 / Sorbat de calciu", risk: 2, desc: "Preservative. Risk of asthma in some. / Conservant. Risc de astm în unele cazuri.", category: "Preservative" },
    { name: "Sodium Acetate", code: "E262", alt: "E262 / Acetat de sodiu", risk: 2, desc: "Acidity regulator. Generally safe. / Regulator de aciditate. General sigur.", category: "Preservative" },
    { name: "Potassium Acetate", code: "E261", alt: "E261 / Acetat de potasiu", risk: 2, desc: "Acidity regulator. Avoid if kidney issues. / Evitați dacă aveți probleme renale.", category: "Preservative" },
    { name: "Lactic Acid", code: "E270", alt: "E270 / Acid lactic", risk: 2, desc: "Safe but can affect infants. / Sigur, dar poate afecta copiii mici.", category: "Acidity Regulator" },
    { name: "Calcium Propionate", code: "E282", alt: "E282 / Propionate de calcium / Propionat de calciu", risk: 2, desc: "Linked to migraines. / Asociat cu migrene.", category: "Preservative" },
    { name: "Sodium Propionate", code: "E281", alt: "E281 / Propionat de sodiu", risk: 2, desc: "Preservative. Can cause sleep disturbances. / Conservant. Poate cauza tulburări de somn.", category: "Preservative" },
    { name: "Lecithin", code: "E322", alt: "E322 / Lecitină", risk: 2, desc: "Natural emulsifier. Often from soy (GMO). / Emulsifiant natural. Deseori din soia (OMG).", category: "Emulsifier" },
    { name: "Sodium Lactate", code: "E325", alt: "E325 / Lactat de sodiu", risk: 2, desc: "Salt of lactic acid. Safe but watch soy/milk source. / Sare a acidului lactic.", category: "Antioxidant" },
    { name: "Potassium Lactate", code: "E326", alt: "E326 / Lactat de potasiu", risk: 2, desc: "Acidity regulator. Safe for adults. / Regulator de aciditate. Sigur pentru adulți.", category: "Antioxidant" },
    { name: "Calcium Lactate", code: "E327", alt: "E327 / Lactat de calciu", risk: 2, desc: "Safe source of calcium. / Sursă sigură de calciu.", category: "Antioxidant" },
    { name: "Citric Acid", code: "E330", alt: "E330 / Acid citric", risk: 2, desc: "Generally safe but can damage teeth enamel. / General sigur, dar poate afecta smalțul dinților.", category: "Acidity Regulator" },
    { name: "Sodium Citrates", code: "E331", alt: "E331 / Citrați de sodiu", risk: 2, desc: "Generally safe. / General sigur.", category: "Acidity Regulator" },
    { name: "Potassium Citrates", code: "E332", alt: "E332 / Citrați de potasiu", risk: 2, desc: "Generally safe. / General sigur.", category: "Acidity Regulator" },
    { name: "Calcium Citrates", code: "E333", alt: "E333 / Citrați de calciu", risk: 2, desc: "Safe calcium supplement. / Supliment sigur de calciu.", category: "Acidity Regulator" },
    { name: "Tartaric Acid", code: "E334", alt: "E334 / Acid tartric", risk: 2, desc: "Safe acidulant. / Acidulant sigur.", category: "Acidity Regulator" },
    { name: "Sodium Tartrates", code: "E335", alt: "E335 / Tartrați de sodiu", risk: 2, desc: "Generally safe. / General sigur.", category: "Acidity Regulator" },
    { name: "Potassium Tartrates", code: "E336", alt: "E336 / Tartrați de potasiu", risk: 2, desc: "Cream of tartar. Safe. / Cremă de tartar. Sigur.", category: "Acidity Regulator" },
    { name: "Orthophosphoric Acid", code: "E338", alt: "E338 / Acid fosforic", risk: 2, desc: "Linked to bone density loss. / Asociat cu scăderea densității osoase.", category: "Acidity Regulator" },
    { name: "Sodium Phosphates", code: "E339", alt: "E339 / Fosfați de sodiu", risk: 2, desc: "May affect kidney function in high doses. / Poate afecta rinichii în doze mari.", category: "Acidity Regulator" },
    { name: "Potassium Phosphates", code: "E340", alt: "E340 / Fosfați de potasiu", risk: 2, desc: "Stabilizer. Safe in moderation. / Stabilizator. Sigur în moderație.", category: "Acidity Regulator" },
    { name: "Calcium Phosphates", code: "E341", alt: "E341 / Fosfați de calciu", risk: 2, desc: "Safe. Common in baking powder. / Sigur. Comun în praful de copt.", category: "Acidity Regulator" },
    { name: "Alpha-Tocopherol", code: "E307", alt: "E307 / Alfa-tocoferol / Vitamina E", risk: 2, desc: "Safe Vitamin E. Watch for source (GMO). / Vitamina E sigură.", category: "Antioxidant" },
    { name: "Sodium Ascorbate", code: "E301", alt: "E301 / Ascorbat de sodiu", risk: 2, desc: "Safe form of Vitamin C. / Formă sigură de Vitamina C.", category: "Antioxidant" },
    { name: "Calcium Ascorbate", code: "E302", alt: "E302 / Ascorbat de calciu", risk: 2, desc: "Safe form of Vitamin C. / Formă sigură de Vitamina C.", category: "Antioxidant" },
    { name: "Agar", code: "E406", alt: "E406 / Agar-agar", risk: 2, desc: "Safe seaweed gelling agent. / Agent de gelifiere natural.", category: "Thickener" },
    { name: "Guar Gum", code: "E412", alt: "E412 / Gomme guar / Gumă guar", risk: 2, desc: "Thickener. Large amounts cause bloating. / Îngroșător. Poate cauza balonare.", category: "Thickener" },
    { name: "Xanthan Gum", code: "E415", alt: "E415 / Gomme xanthane / Gumă xantan", risk: 2, desc: "Emulsifier. May cause digestive issues. / Emulsifiant. Probleme digestive.", category: "Emulsifier" },
    { name: "Gellan Gum", code: "E418", alt: "E418 / Gumă gellan", risk: 2, desc: "Gelling agent. Generally safe. / Agent de gelifiere. General sigur.", category: "Thickener" },
    { name: "Glycerol", code: "E422", alt: "E422 / Glicerină / Glicerol", risk: 2, desc: "Safe sweetener/humectant. / Îndulcitor/umectant sigur.", category: "Humectant" },
    { name: "Malic Acid", code: "E296", alt: "E296 / Acid malic", risk: 2, desc: "Natural apple acid. Safe. / Acid natural din mere. Sigur.", category: "Acidity Regulator" },
    { name: "Fumaric Acid", code: "E297", alt: "E297 / Acid fumaric", risk: 2, desc: "Acidity regulator. Safe in small doses. / Regulator de aciditate. Sigur.", category: "Acidity Regulator" },
    { name: "Triphosphates", code: "E451", alt: "E451 / Trifosfați", risk: 2, desc: "Stabilizer. High doses are harmful. / Stabilizator. Periculos în doze mari.", category: "Stabilizer" },
    { name: "Polyphosphates", code: "E452", alt: "E452 / Polifosfați", risk: 2, desc: "Thickener. Can slow minerals absorption. / Poate încetini absorbția mineralelor.", category: "Thickener" },
    { name: "Maltitol", code: "E965", alt: "E965 / Sirop de maltitol", risk: 2, desc: "Can have a laxative effect. / Poate avea efect laxativ.", category: "Sweetener" },
    { name: "Xylitol", code: "E967", alt: "E967 / Xilitol", risk: 2, desc: "Laxative in humans. Toxic to dogs. / Laxativ. Toxic pentru câini.", category: "Sweetener" },
    { name: "Sorbitol", code: "E420", alt: "E420 / Sirop de sorbitol", risk: 2, desc: "Sugar substitute with laxative properties. / Îndulcitor cu proprietăți laxative.", category: "Sweetener" },
    { name: "Erythritol", code: "E968", alt: "E968 / Eritritol", risk: 2, desc: "Safe sugar alcohol. Generally well tolerated. / Îndulcitor natural sigur.", category: "Sweetener" },
    { name: "Modified Corn Starch", code: "STARCH", alt: "Fécule de maïs modifiée / Amidon modificat", risk: 2, desc: "Processed thickener. / Îngroșător procesat.", category: "Thickener" },
    { name: "Palm Oil", code: "PALM", alt: "Palm fat / Huile de palme / Ulei de palmier / Grăsime vegetală de palmier", risk: 2, desc: "High saturated fats. / Grăsimi saturate ridicate.", category: "Fats" },
    { name: "Sugar", code: "SUGAR", alt: "Glucose-fructose / Sucres / Zahăr / Zaharuri", risk: 2, desc: "Leading cause of obesity and diabetes. / Cauză principală a obezității.", category: "Sweetener" },
    { name: "High Fructose Corn Syrup", code: "HFCS", alt: "HFCS / Sirop de porumb bogat în fructoză", risk: 2, desc: "Highly refined sweetener. / Îndulcitor foarte rafinat.", category: "Sweetener" },
    { name: "Salt", code: "SALT", alt: "Sel / Sare / Clorură de sodiu", risk: 2, desc: "High intake leads to high blood pressure. / Consumul ridicat duce la hipertensiune.", category: "Mineral" },

    // --- LOW RISK (Category 1: SAFE / NATURAL) ---
    { name: "Ascorbic Acid", code: "E300", alt: "E300 / Acide ascorbique / Acid ascorbic / Vitamina C", risk: 1, desc: "Vitamin C. Essential nutrient. / Vitamina C. Nutrient esențial.", category: "Antioxidant" },
    { name: "Tocopherols", code: "E306", alt: "E306 / Tocoferol / Vitamina E naturală", risk: 1, desc: "Natural Vitamin E. Very safe. / Vitamina E naturală. Foarte sigură.", category: "Antioxidant" },
    { name: "Beeswax", code: "E901", alt: "E901 / Ceară de albine", risk: 1, desc: "Natural glazing agent. Safe. / Agent natural de glazurare. Sigur.", category: "Glazing Agent" },
    { name: "Candelilla Wax", code: "E902", alt: "E902 / Ceară candelilla", risk: 1, desc: "Natural plant wax. Safe. / Ceară vegetală naturală. Sigură.", category: "Glazing Agent" },
    { name: "Shellac", code: "E904", alt: "E904 / Șerlac", risk: 1, desc: "Natural resin. Safe. / Rășină naturală. Sigură.", category: "Glazing Agent" },
    { name: "Acetic Acid", code: "E260", alt: "E260 / Acid acetic / Oțet", risk: 1, desc: "Main component of vinegar. Safe. / Componenta principală a oțetului.", category: "Preservative" },
    { name: "Carbonated Water", code: "WATER", alt: "Eau gazéifiée / Apă carbogazoasă / Apă minerală", risk: 1, desc: "Standard sparkling water. / Apă minerală standard.", category: "Liquid" },
    { name: "Natural Flavour", code: "FLAVOUR", alt: "Arôme naturel / Aromă naturală", risk: 1, desc: "Extracted from natural sources. / Extras din surse naturale.", category: "Flavour" },
    { name: "Pectin", code: "E440", alt: "E440 / Pectină", risk: 1, desc: "Natural fiber from fruits. / Fibră naturală din fructe.", category: "Thickener" },
    { name: "Carob Bean Gum", code: "E410", alt: "E410 / Gumă de caruba", risk: 1, desc: "Natural thickener. Very safe. / Îngroșător natural. Foarte sigur.", category: "Thickener" }
];
